### ISSUE TITLE
getElementByPath: No dots [.] in path possible

### ISSUE THREAD

**Issue by uwsrf** [nrkno/tv-automation-emberplus-connection#17]
Since there is a fixed coding of the path limiter on line 359 in "/src/Ember/Client/index.ts", there is no possibility to use this library with Ember+-devices using dots in their path-names. Having the delimiter as an optional argument to `getElementByPath()` would be great.

**Comment by mint-dewit** [comment]
Well, it's not impossible to use the library since you can use paths as they are used for qualified elements: using only numbers and dots. 

That being said, it not as convenient and I see little harm in making the delimiter an optional argument as using identifiers or descriptions is outside of the specification anyway. PR is welcome or else I'll get to it one day...
